### ISSUE TITLE
Possibility to add certs for https

### ISSUE THREAD

**Issue by surudoiryu** [verdaccio/ansible-verdaccio#13]
As a user i would like to make it possible to add and change the location for ssl certificates for a more secure connection.

Configure HTTPS, it is required if you use "https" protocol above.
```
https:
  key: path/to/server.key
  cert: path/to/server.crt
```
https://github.com/verdaccio/verdaccio/blob/master/conf/full.yaml#L104

**Comment by 030** [comment]
can be done using a rproxy
