### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by 030** [verdaccio/ansible-verdaccio#22]
I would like to start to maintain this role like I did back in the day. Would that be possible?

**Comment by juanpicado** [comment]
Absolutely 👍

**Comment by juanpicado** [comment]
I gave you `Maintainer` role, your help is very welcome 👏

**Comment by 030** [comment]
@juanpicado thank you :)

**Comment by juanpicado** [comment]
You should be able to:
* Update label
* Merge without restrictions
* Organize labels
* and what you consider is required 

etc etc, the code base is quite old, so I don't expect there is much traffic, the unique restriction is don't change the license which must be on MIT and code of conduct is based on the main repo https://github.com/verdaccio/verdaccio/blob/master/CODE_OF_CONDUCT.md

:)

**Comment by juanpicado** [comment]
Thank u @030

**Comment by 030** [comment]
@juanpicado Thank you. License kept to MIT. Update of role done.
