### ISSUE TITLE
/usr/local/bin/verdaccio cannot be found. 

### ISSUE THREAD

**Issue by kai-chu** [verdaccio/ansible-verdaccio#24]
Inventory CentOS8

Problem: 
After verdaccio installed, service cannot be started due to /usr/local/bin/verdaccio cannot be found

Try to resolve:
Run command in remote host `npm config get prefix`, it points to /usr/local/lib/npm/bin
Also in the dependency, there is a task to setup the prefix.
```
TASK [geerlingguy.nodejs : Add npm_config_prefix bin directory to global $PATH.] *****************************************************
```
Solutions to fix:
1. Explicitly add npm_config_prefix to host vars if any user wants to use this role
2. Get npm_config_prefix in this role
```
// tasks/main.yml
- name: resolve npm config path
  command: npm config get prefix 
  register: npm_config_prefix_resolve

- set_fact: npm_config_prefix="{{ npm_config_prefix_resolve.stdout }}"

// templates/verdaccio.service.j2
ExecStart={{ npm_config_prefix }}/bin/verdaccio -c {{ verdaccio_configdir }}/verdaccio.yml
```

**Comment by juanpicado** [comment]
hi @kai-chu 

would you like to open a PR?

**Comment by 030** [comment]
2.0.1

**Comment by 030** [comment]
@kai-chu  https://travis-ci.org/github/verdaccio/ansible-verdaccio/jobs/717701959 The build failed. Could you fix it?

**Comment by kai-chu** [comment]
yes!

> @kai-chu https://travis-ci.org/github/verdaccio/ansible-verdaccio/jobs/717701959 The build failed. Could you fix it?

I was trying to add a trailing line and the merge was done before I try to fix it. Wait a sec. Fixing now

**Comment by kai-chu** [comment]
@030  Check the pull request

**Comment by 030** [comment]
```
    /home/travis/build/verdaccio/verdaccio.verdaccio/tasks/main.yml

      22:44     error    trailing spaces  (trailing-spaces)

      23:59     error    trailing spaces  (trailing-spaces)

      25:1      error    trailing spaces  (trailing-spaces)
```

**Comment by 030** [comment]
The travis molecule itself seems to be broken as well. It is unclear why the get of the py fails.

**Comment by 030** [comment]
2.0.1 https://galaxy.ansible.com/verdaccio/ansible-verdaccio
