### ISSUE TITLE
Info for pinned repo

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ansible-verdaccio#30]
I'm really proud of this repo 💯 . So I was thinking to pinned to give it more visbility.

<img width="1053" alt="Screen Shot 2020-09-09 at 10 43 08 PM" src="https://user-images.githubusercontent.com/558752/92652890-dc92ca80-f2ed-11ea-9c54-d014d1dc1a3b.png">

@030 could you figure out something for the **about** section ?

**Comment by 030** [comment]
@juanpicado An about section has been added. Could you check it and let me know if it is sufficient?

**Comment by juanpicado** [comment]
great thanks !
